# Numpy Basics <hr style= "border:2.5px solid #126782"></hr> 

Data Analyst: Marc Lester Salvador <br> Department: Electrical Engineering


# install and update NumPy

In [1]:
#%pip install numpy --upgrade

# install and update scipy

In [2]:
#%pip install scipy --upgrade

In [3]:
#imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [4]:
# 1-dimensional array
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [5]:
# size on an array
np.shape(array_a)


(3,)

In [6]:
# 1-dimensional array
my_array = np.array([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

# 2D Array

In [7]:
# 2-dimensional array
my_array = np.array ([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# size of matrix
np.shape(my_array)

(2, 3)

In [9]:
#transpose of a matrix 
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
#size of matrix
np.shape(t_array)

(3, 2)

# Measures of Central Tendency

In [12]:
# fruit price list dataset
fruits = np.array ([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [13]:
# mean
fruits_mean = np.mean(fruits)
fruits_mean

123.0

In [14]:
# mean
fruits_median = np.median(fruits)
fruits_median

120.0

In [15]:
# mean
fruits_sorted = np.sort(fruits)
fruits_sorted

array([ 60,  85, 120, 150, 200])

In [ ]:
# mode
stats.mode(fruits)

 # Jaguar vs Panther

# Jaguar

In [16]:
jaguar = np.array ([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [17]:
jag_mean = np.mean(jaguar)
jag_mean

9.399999999999999

In [18]:
jag_median = np.median(jaguar)
jag_median

9.8

In [25]:
jag_mode = stats.mode(jaguar)
jag_mode

ModeResult(mode=9.8, count=2)

In [26]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

8.0

In [27]:
# Q1 
q1_jag = np.percentile(jaguar,25)
q1_jag

9.4

In [28]:
# Q2 (median)
q2_jag = np.percentile(jaguar,50)
q2_jag

9.8

In [29]:
# Q3
q3_jag = np.percentile(jaguar,75)
q3_jag

10.45

In [30]:
#IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

1.049999999999999

In [31]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

4.86

# Panther

In [20]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [21]:
pan_mean = np.mean(panther)
pan_mean

10.75

In [22]:
pan_median = np.median(panther)
pan_median

9.55

In [23]:
pan_mode = stats.mode(panther)
pan_mode

ModeResult(mode=9.1, count=3)

In [24]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan

10.9

In [33]:
# Q1 
q1_pan = np.percentile(panther,25)
q1_pan

9.125

In [34]:
# Q2 (median)
q2_pan = np.percentile(panther,50)
q2_pan

9.55

In [35]:
# Q3
q3_pan = np.percentile(panther,75)
q3_pan

10.625

In [36]:
#IQR
iqr_pan = q3_pan - q1_pan
iqr_pan

1.5

In [37]:
# sample variance
var_pan = np.var(panther,ddof=1)
var_pan

11.082777777777777